# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitTrending' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for GitTrending
  
  # Alamofire : HTTP networking library
  # refs -> https://github.com/Alamofire/Alamofire
  pod 'Alamofire'
  
  # AlamofireImage : Image component library for Alamofire
  # refs -> https://github.com/Alamofire/AlamofireImage
  pod 'AlamofireImage'
  
  # AlamofireNetworkActivityIndicator : Controls the visibility of the network activity indicator using Alamofire
  # refs -> https://github.com/Alamofire/AlamofireNetworkActivityIndicator
  pod 'AlamofireNetworkActivityIndicator'

  # SwiftSoup :  Pure Swift HTML Parser, with best of DOM, CSS, and jquery
  # refs -> https://github.com/scinfu/SwiftSoup
  pod 'SwiftSoup'
  
  target 'GitTrendingTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'GitTrendingUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
