# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitTrending' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for GitTrending
  
  # Alamofire is an HTTP networking library
  # refs -> https://github.com/Alamofire/Alamofire
  pod 'Alamofire'
  
  target 'GitTrendingTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'GitTrendingUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
